spring:
  jpa:
    show-sql: true
  datasource:
    username: username
    password: password
    url: jdbc:postgresql://localhost:5434/app_db
    driver-class-name: org.postgresql.Driver

management:
  auth:
    user:
      name: admin
      password: admin

application:
  cors:
    origins: http://localhost:4200