version: '3.1'

services:
  database:
    image: postgres:12
    container_name: app-db
    restart: always
    env_file:
      - database.env
    ports:
      - 5434:5432
    volumes:
      - app-db-data:/var/lib/postgresql/data/

volumes:
  app-db-data:
